# Cloudflare Worker - Shorten Link Transmigrasi
name = "shotlink-kementras"
main = "_worker.js"
compatibility_date = "2026-09-26"

[assets]
directory = "./public"
binding = "ASSETS"

# KV Namespace binding untuk menyimpan data (user, link, session)
[[kv_namespaces]]
binding = "LINKS"
id = "3fe80920bc094c1dbb31424170300420"

# Variable env - bisa juga diatur lewat Cloudflare Dashboard:
# Workers & Pages > shotlink-kementras > Settings > Variables and Secrets
#
# [vars]
# ADMIN_USERNAMES = "admin"
# ALLOW_REGISTRATION = "false"

